### ISSUE TITLE
ddclient no ip found but works via command line

### ISSUE THREAD

**Issue by paulmorabito** [linuxserver/docker-ddclient#11]
Hi,

I'm running Ubuntu 18.04 and ddclient within a docker container. I've configured my ddclient.conf however, when running from the daemon I get the following error:

ddclient         | 2018-08-08T08:56:21.253119508Z WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''

However, if I run:

ddclient -file=/config/ddclient.conf -daemon=0 -debug -verbose -noquiet

from within the container then the IP is found and updated.

My docker compose yml for the container is:

  ddclient:
    image: "linuxserver/ddclient"
    container_name: "ddclient"
    volumes:
      - ${USERDIR}/docker/ddclient:/config
    restart: always
    environment:
      - PUID=xxxx
      - PGID=xxx
      - TZ=${TZ}

Any ideas on how to correct this?

**Comment by paulmorabito** [comment]
Hi,

UID is 1000 and GID is 996. I can verify this is being set correctly within
the container because when the container starts up I can see the uid and
gid displayed in the logs.

I can confirm I have enabled "use web=yes". I also had:

use=if,                     if=enp2s0

Which I disabled and deleted the file in the original error. The inotify on
the file triggered an update and I got:

ddclient         | 2018-08-08T23:59:54.355070989Z /config/ddclient.conf
MODIFY

ddclient         | 2018-08-08T23:59:54.380211119Z ddclient has been
restarted

ddclient         | 2018-08-08T23:59:54.389695760Z WARNING:  file
/var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip'
= ''

ddclient         | 2018-08-08T23:59:54.389770479Z Setting up watches.

ddclient         | 2018-08-08T23:59:54.389798802Z Watches established.

ddclient         | 2018-08-08T23:59:55.093183655Z WARNING:  skipping update
of xxxx.net from <nothing> to 61.78.85.210.

ddclient         | 2018-08-08T23:59:55.093237994Z WARNING:   last updated
<never> but last attempt on Thu Aug  9 08:55:11 2018 failed.

ddclient         | 2018-08-08T23:59:55.093252395Z WARNING:   Wait at least
5 minutes between update attempts.

ddclient         | 2018-08-09T00:09:56.367877457Z WARNING:  file
/var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip'
= ''

So the same problem persists.

**Comment by tobbenb** [comment]
Do you have use=web or use web=yes?
It should be use=web.
Did you try to delete the ddclient.cache file as I suggested?

**Comment by nightah** [comment]
@paulmorabito which provider are you updating?
It's not Cloudflare is it?

**Comment by paulmorabito** [comment]
yes, it's cloudfare.

i have web=yes, sorry that was a typo. And yes, I tried to delete the file
in question and the error reoccurs.

**Comment by nightah** [comment]
The issue you're experiencing is to do with the fact that the current client uses the old deprecated Cloudflare API as per #12.

**Comment by paulmorabito** [comment]
Ok I see. I'll wait for the new release then. Thanks.
