### ISSUE TITLE
Cloudflare API v1 End of Life on November 9th, 2016

### ISSUE THREAD

**Issue by nightah** [linuxserver/docker-ddclient#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Due to the [deprecation of the v1 Cloudflare API](https://blog.cloudflare.com/sunsetting-api-v1-in-favor-of-cloudflares-current-client-api-api-v4/) the current version of ddclient cannot update any Cloudflare based hosts.

There is a fix for this in the [upstream github repo](https://github.com/ddclient/ddclient/pull/42) however since then no new releases have been tagged/made.

Could we update the container to utilise the upstream code instead of the release on sourceforce?
Seems they're both maintained by wimpunk, however the upstream GitHub repo is maintained actively.

Happy to submit a PR if this will be considered as an option.

**Comment by tobbenb** [comment]
Have they moved the development to github? I'm not so keen on using development branches.

**Comment by nightah** [comment]
@wimpunk appears to maintain both the sourceforge page for ddclient and that same upstream github repo.

They have mentioned that the v3.9.0 release is currently being prepped: https://github.com/ddclient/ddclient/pull/42.

**Comment by tobbenb** [comment]
Then I'll wait for that. Feel free to make a PR if you want 🙂

**Comment by nightah** [comment]
@tobbenb, done #13.
