### ISSUE TITLE
multiple domain with namecheap.com not working

### ISSUE THREAD

**Issue by jodumont** [linuxserver/docker-ddclient#15]
Hi;

I tried different configuration and found this
https://thornelabs.net/2012/08/22/linux-make-ddclient-work-with-multiple-namecheap-domains.html
where it explain exactly my issue

I'm using namecheap and having same subdomain on different domain.tld and only the last one is updating the ip.

apparently still missing in ddclient 3.9

_REMARK: I made an ddclient image with bionic installed via apt get
which result of ddclient version 3.8.3
and everything works fine_

So don't know if it's possible to validate this behavior and/or update your image by including the patch

On my side; I'll see if I'm able to make a PR

Thanks!

**Comment by homerr** [comment]
I'm confused now, I've read this support is in 3.8.3 which came before 3.9 and this container is building using 3.9 so it should work?

**Comment by jodumont** [comment]
yes it should, but it's not

**Comment by icolwell** [comment]
See [this bug report](https://sourceforge.net/p/ddclient/bugs/89/) for a possible cause.

**Comment by jodumont** [comment]
@icolwell thank you for following :)

@homerr 
since the issue is more from ddclient side than linuxserver; I'll close this issue.

**Comment by icolwell** [comment]
@jodumont: No problem, I came across your post after having similar issues. 
I've opened a PR with a fix if you are interested:
https://github.com/ddclient/ddclient/pull/64
