### ISSUE TITLE
missing perl module for ipv6

### ISSUE THREAD

**Issue by Byter09** [linuxserver/docker-ddclient#18]
OS:
`Linux BTR-SRV 4.20.11-1-MANJARO #1 SMP PREEMPT Wed Feb 20 23:19:36 UTC 2019 x86_64 GNU/Linux`

`ddclient.conf`:
<pre><code>
protocol=dyndns2
use=web, web=ipv4.icanhazip.com
server=www.ovh.com
login=XXX
password='XXX'
XXX

protocol=cloudflare
use=web, web=ipv4.icanhazip.com
zone=XXX
ttl=1
login=XXX
password='XXX'
XXX

<b>protocol=cloudflare
ipv6=yes
use=web, web=ipv6.icanhazip.com
zone=XXX
ttl=1
login=XXX
password='XXX'
XXX</b>
</code></pre>

So, sadly enough my ISP uses dynamic IPv6 addresses (which is I guess good for security?), and I'm trying the above config. The highlighted block causes the following container log output:
```
FATAL:    Error loading the Perl module IO::Socket::INET6 needed for ipv6 connect.,
FATAL:     On Debian, the package libio-socket-inet6-perl must be installed.,
FATAL:     On Red Hat, the package perl-IO-Socket-INET6 must be installed.,
FATAL:     On Alpine, the package perl-io-socket-inet6 must be installed.
```
I'm assuming that this is simply missing in the image?

Is this an oversight in the https://github.com/linuxserver/docker-ddclient/pull/13 PR?

I can also open a PR if it is simply the missing `perl-io-socket-inet6` in this part of the dockerfile:
https://github.com/linuxserver/docker-ddclient/blob/8d191244c707b88392689954cbf0aaf55b4256fb/Dockerfile#L26
but I'm not quite sure about ARM etc.

Thank you for taking the time to look at this issue :)

**Comment by aptalca** [comment]
PR would be appreciated. It should be the same package for armhf and aarch64: https://pkgs.alpinelinux.org/packages?name=perl-io-socket-inet6&branch=v3.9

Thanks

**Comment by aptalca** [comment]
Also, the PR will be built by our jenkins and pushed to docker hub at `lspipepr/ddclient`, which you can pull to test and make sure it solves your issue
