### ISSUE TITLE
Errors when using -force or running manually

### ISSUE THREAD

**Issue by HeyRobb** [linuxserver/docker-ddclient#23]
Hello All,

   I am getting the following errors while running the following commands within Docker container:

root@0ca88883e2e4:/# ddclient -force
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1117.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1118.
readline() on closed filehandle FD at /usr/bin/ddclient line 1130.
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1117.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1118.
readline() on closed filehandle FD at /usr/bin/ddclient line 1130.
root@0ca88883e2e4:/#

root@0ca88883e2e4:/# ddclient -daemon=0 -debug -verbose -noquiet
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1117.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1118.
readline() on closed filehandle FD at /usr/bin/ddclient line 1130.
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
stat() on closed filehandle FD at /usr/bin/ddclient line 1117.
Use of uninitialized value $mode in bitwise and (&) at /usr/bin/ddclient line 1118.
readline() on closed filehandle FD at /usr/bin/ddclient line 1130.
=== opt ====
opt{cache}                           : <undefined>
opt{cmd}                             : <undefined>
opt{cmd-skip}                        : <undefined>
opt{daemon}                          : 0
opt{debug}                           : 1
opt{exec}                            : <undefined>
opt{facility}                        : <undefined>
opt{file}                            : <undefined>
opt{force}                           : <undefined>
opt{foreground}                      : <undefined>
opt{fw}                              : <undefined>
opt{fw-banlocal}                     : <undefined>
opt{fw-login}                        : <undefined>
opt{fw-password}                     : <undefined>
opt{fw-skip}                         : <undefined>
opt{geturl}                          : <undefined>
opt{help}                            : <undefined>
opt{host}                            : <undefined>
opt{if}                              : <undefined>
opt{if-skip}                         : <undefined>
opt{ip}                              : <undefined>
opt{ipv6}                            : <undefined>
opt{login}                           : <undefined>
opt{mail}                            : <undefined>
opt{mail-failure}                    : <undefined>
opt{max-interval}                    : 2160000
opt{min-error-interval}              : 300
opt{min-interval}                    : 30
opt{options}                         : <undefined>
opt{password}                        : <undefined>
opt{pid}                             : <undefined>
opt{postscript}                      : <undefined>
opt{priority}                        : <undefined>
opt{protocol}                        : <undefined>
opt{proxy}                           : <undefined>
opt{query}                           : <undefined>
opt{quiet}                           : 0
opt{retry}                           : <undefined>
opt{server}                          : <undefined>
opt{ssl}                             : <undefined>
opt{syslog}                          : <undefined>
opt{test}                            : <undefined>
opt{timeout}                         : <undefined>
opt{use}                             : <undefined>
opt{verbose}                         : 1
opt{web}                             : <undefined>
opt{web-skip}                        : <undefined>
=== globals ====
globals{daemon}                      : 60
globals{debug}                       : 1
globals{quiet}                       : 0
globals{verbose}                     : 1
=== config ====
=== cache ====
cache{@}{atime}                      : 0
cache{@}{host}                       : @
cache{@}{ip}                         : my.correctWAN.IP.Here
cache{@}{mtime}                      : 1566325878
cache{@}{status}                     : good
cache{@}{warned-min-error-interval}  : 0
cache{@}{warned-min-interval}        : 0
cache{@}{wtime}                      : 30
cache{my.domain}{atime}              : 0
cache{my.domain}{host}               : my.domain
cache{my.domain}{ip}                 : my.correctWAN.IP.Here
cache{my.domain}{mtime}              : 1566325878
cache{my.domain}{status}             : good
cache{my.domain}{warned-min-error-interval} : 0
cache{my.domain}{warned-min-interval} : 0
cache{my.domain}{wtime}              : 30
root@0ca88883e2e4:/#

Here is what the contents of my ddclient.conf are:

daemon=600                              # check every 600 seconds
syslog=yes                              # log update msgs to syslog
protocol=zoneedit1
use=web, web=dyndns
server=dynamic.zoneedit.com
login=usernamehere
password=passwordhere
my.domain
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=my.domain2
password=passwordhere
@

As you can see, there is neither a 'config' section within the manual-run output, nor is there any data from my second domain, my.domain2 (via namecheap) in the cache or other outputs. Any help would be greatly appreciated!

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 16.04.3 LTS / Docker 19.03.1

Docker-compose:

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${D_DRIVE}/ddclient:/config
    restart: always

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
Setting up watches.
Watches established.
[services.d] done.

No symlinks

**Comment by tobbenb** [comment]
Don't run any commands inside the container.
Any edits to the config file restarts ddclient.
