### ISSUE TITLE
Configuration not applied when following docs

### ISSUE THREAD

**Issue by tstivers1990** [linuxserver/docker-ddclient#25]
## Expected Behavior
ddclient should start and use the configuration file in the volume

## Current Behavior
ddclient is set to use /ddclient.conf in the dockerfile instead of /config/ddclient.conf and ends up always using the default conf when following the provided instructions. The instructions assume ddclient is looking for the configuration in /config/ddclient.conf.

## Command used to create docker container (run/create/compose/screenshot)
```bash
docker create \
  --name=ddclient \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -v path to data:/config \
  --restart unless-stopped \
  linuxserver/ddclient
```

It appears this is desired behavior. But, when mounting an existing folder using `-v /mnt/data:/config`, it does not seem to be copying the updated `/config/ddclient.conf` to `/ddclient.conf` after an update.

**Comment by CHBMB** [comment]
@tstivers1990 You need to map a local folder to `/config`

**Comment by tstivers1990** [comment]
> @tstivers1990 You need to map a local folder to `/config`

I am doing this. In my case, I used the `-v /mnt/npm/ddclient:/config` parameter. After looking deeper at the source, I realize there is a script that's supposed to copy `/config/ddclient.conf` to `/ddclient.conf` when `/config/ddclient.conf` is changed. But that doesn't seem to be working in my scenario.

I'm using CoreOS stable.

**Comment by tstivers1990** [comment]
It seems I misconfigured the setup and the volume was somehow broken and not actually a bind mount as intended. Closing this as PEBKAC.
