### ISSUE TITLE
file permission on ddclient.conf

### ISSUE THREAD

**Issue by davxiao** [linuxserver/docker-ddclient#26]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

ddclient.conf has permissions "-rwxrw-r-x " and after I changed it to 600, it was again overwritten by ddclient when container is restored
------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      alpine linux 
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by CHBMB** [comment]
I can reproduce this.  Looks like we chmod during init the `ddclient.conf` to 600, then subsequently recursively chmod `/config` subsequently.  

https://github.com/linuxserver/docker-ddclient/blob/master/root/etc/cont-init.d/30-config#L18-L25

**Comment by CHBMB** [comment]
@davxiao Can you pull this image 
`lspipepr/ddclient:3.9.0-pkg-7db5d2ed-pr-28`
That is the image for the PR above.

If you can confirm that it

1. Fixes the issue you're seeing
2. Doesn't throw any errors

Then we should be good.
