### ISSUE TITLE
Can't obtain IP

### ISSUE THREAD

**Issue by davidosomething** [linuxserver/docker-ddclient#33]
Had to mark my host configs with `use=web, web=checkip.amazonaws.com` each since I think the default method of using `ip` is not available in the base image?

**Comment by modem7** [comment]
Would also like to see an exit code 1 if it fails so that we can have an unhealthy container option

**Comment by tobbenb** [comment]
It's up to the ddclient developers to make ddclient fail with an exit code.

As for the OP, I just looked at the documentation, but doesn't say anything about any special dependencies.
So you set the config to use=ip -ip {IP address} and that doesn't work?

**Comment by davidosomething** [comment]
yea it was logging out the standard cannot obtain ipv4 ipv6 message because the method of getting `ip` didn't work

**Comment by tobbenb** [comment]
It just uses the ip binary? Then it probably doesn't have access or the problem is that it's the busybox version.
A simple test is to install the package that have the IP binary and check again.

From the documentation I read it looked like you also had to supply an IP using the ip option.

**Comment by davidosomething** [comment]
just going to close this -- pretty sure it has to do with docker host iptables

you shouldn't have to provide ip manually, that's one of ddclient's two primary purposes (the other being sending that ip to the dns service)

**Comment by tobbenb** [comment]
I interpreted it as an IP to get the public IP from. Didn't find much info in my short search.
