### ISSUE TITLE
Version-only Tags to allow automatic updates

### ISSUE THREAD

**Issue by jan-di** [linuxserver/docker-ddclient#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

Add version tags to the automatic build routine to allow automatic updates via watchtower etc. without breaking compatability

------------------------------

## Expected Behavior
Additional to the automatic tags (vX.Y.Z-lsXY) there should be a version-only tags that specify the major/minor versions (vX, vX.Y, vX.Y.Z)

## Current Behavior
Can either use a specific version number, that is never updated or use the latest tag, that does not provide backward compatability due to possible major updates.

**Comment by tobbenb** [comment]
I don't really see the point doing what you suggest as you can set a specific tag already. This is a part of our build system and will not be changed.
The first part is the app version, while the last part lsXY is our build number. We push a new release if there is a OS package that is updated.

**Comment by jan-di** [comment]
Tahnk you for your response. I will try to explain you my point a little bit more: I see that i can point to a specific version, but that means the combination of programm version and os-update-level (lsXY). 

What my wish is, for example a tag like "3.9" for ddclient. If I would use this tag, it would allow me to safeley pull the image again and update it
- without breaking compatability (as the tag only moves along 3.9.x releases)
- get the current os update level. 
This could be automated. That has the advantage of getting bugfixes automatically, but no major version upgrades (as it is the case with the latest tag)

When in future v3.9.2 would come out, the tag would be moved forward to this version.

**Comment by aptalca** [comment]
We don't have plans to do that for ddclient. We only do it for apps that support multiple stable version tracks simultaneously like unifi and go
