### ISSUE TITLE
UID corrupts host filesystem

### ISSUE THREAD

**Issue by andig** [linuxserver/docker-ddclient#37]
Running the image changes host filesystem permissions and makes scripts unexecutable

------------------------------

## Expected Behavior
Running script should not change host filesystem/ volume mount permissions

## Current Behavior
Running script changes owner of config folder to 911 and removes executable permission:

    admin@NAS:~$ ls -l /volume1/data/docker/
    total 112
    drwx------  3   911   911 4096 Jun  8 08:23 ddclient
    drwxrwxrwx  3 admin users 4096 Jan  7  2018 dnsmasq

## Steps to Reproduce
1. configure docker container

        ddclient:
          container_name: ddclient
          image: linuxserver/ddclient
          volumes:
          - /volume1/data/docker/ddclient:/config
          environment:
          - TZ=Europe/Berlin
          restart: always

2. run container
3. after running container the mapped config folder
  - is no longer owned by admin but by 911
  - executable permissions are removed and folder cannot be ls'ed from the host
  - executable scripts inside the folder can no longer be executed

## Environment
**OS:**      Synology NAS
**CPU architecture:** x86_64
**How docker service was installed:**      
docker-compose, see above

## Docker logs

    To support LSIO projects visit:
    https://www.linuxserver.io/donate/
    -------------------------------------
    GID/UID
    -------------------------------------
    User uid:    911
    User gid:    911
    -------------------------------------
    [cont-init.d] 10-adduser: exited 0.
    [cont-init.d] 30-config: executing... 
    [cont-init.d] 30-config: exited 0.
    [cont-init.d] 99-custom-files: executing... 
    [custom-init] no custom files found exiting...
    [cont-init.d] 99-custom-files: exited 0.
    [cont-init.d] done.
    [services.d] starting services
    [services.d] done.
    Setting up watches.
    Watches established.
    Can't exec "/config/fritzip.sh": Permission denied at /usr/bin/ddclient line 2234.
    Can't exec "/config/fritzip.sh": Permission denied at /usr/bin/ddclient line 2234.
    WARNING:  found neither ipv4 nor ipv6 address
    Can't exec "/config/fritzip.sh": Permission denied at /usr/bin/ddclient line 2234.
    WARNING:  found neither ipv4 nor ipv6 address
    WARNING:  found neither ipv4 nor ipv6 address
    /config/ddclient.conf MODIFY 
    ddclient has been restarted
    Setting up watches.
    Watches established.

**Comment by tobbenb** [comment]
You haven't followed our info in the readme and didn't map user or group id. 
We use that so the files written in the mounted volumes or host bind mounted folders use the same user. 
So if you would have set that variable, the container wouldn't have change the permissions on those files.
Another reason we do it this way, is to make sure the application can read, write and execute the files in the /config folder.

**Comment by andig** [comment]
Thank you, that fixed the changed folder permissions. It would still be great to not reset the +x flag of contained scripts?

**Comment by tobbenb** [comment]
The config folder is only for the apps/containers config files, so there shouldn't be anything else in there than what the container creates. We set it to 600 and 700 according to what ddclient wants the permissions on the files to be.

Is there any use case for adding any scripts in the /config folder?

**Comment by andig** [comment]
> Is there any use case for adding any scripts in the /config folder?

I've noticed that the sample scripts from https://github.com/ddclient/ddclient are not part of the image and wanted to add those for use with `cmd`. Doesn't have to be in the config folder though and I've just added a separate mount with `/usr/local/bin/<scriptfile>` as target.

Happy to treat this as solved, thank you!

**Comment by tobbenb** [comment]
Of all the sample scripts, I only see one that might be needed and that is the fritz box one. The others are not needed as the container has it's own process monitoring and init system.

**Comment by andig** [comment]
That‘s exactly what I‘ve added :)

**Comment by tobbenb** [comment]
I'll have a look and see if it's possible to change the chmod so it only does it on the files needed so a scripts folder will not loose the execute flag.

**Comment by sepo83** [comment]
For me the following workaround works:

Add a file `/config/custom-cont-init.d/set-permissions.sh`:
````
#!/usr/bin/with-contenv bash
chmod +x /config/get-ip-from-fritzbox.sh
````

... of course, `/config/get-ip-from-fritzbox.sh` has to be replaced with the script you want to execute :)
