### ISSUE TITLE
ddclient doesn't update the dns settings regularly

### ISSUE THREAD

**Issue by szaimen** [linuxserver/docker-ddclient#40]
# Expected behaviour
ddclient updates the dns settings regularly

# Current behaviour
ddclient doesn't update the dns settings regularly

# Steps to Reproduce & Command used to create docker container (run/create/compose/screenshot)
https://github.com/nextcloud/vm/blob/3fedd8887ec7ad3d9f4e18fd3ce62a945920de7f/network/ddclient-configuration.sh#L143-L189

# Environment
platform is x86 Ubuntu 20.04 LTS, docker was installed by `curl -fsSL get.docker.com | sh`
`

# docker logs
```
Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    65534
User gid:    65534
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
Setting up watches.
Watches established.
``

**Comment by szaimen** [comment]
Alternatively, I could create a cronjob that executes the following every 5 min or so:
` docker exec --user nobody ddclient bash -c "ddclient -file /config/ddclient.conf" &>/dev/null`
But it would be nicer if the service/cronjob was included inside the container or if it would work.

**Comment by aptalca** [comment]
It does update regularly. Ddclient runs continuously in the foreground:
https://github.com/linuxserver/docker-ddclient/blob/master/root/etc/services.d/ddclient/run#L3

**Comment by aptalca** [comment]
By default it checks every 5 minutes:
https://github.com/linuxserver/docker-ddclient/blob/master/root/defaults/ddclient.conf#L19
