### ISSUE TITLE
Add IPv6 patches from Debian

### ISSUE THREAD

**Issue by rugk** [linuxserver/docker-ddclient#49]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Debian [added some patches](https://github.com/ddclient/ddclient/blob/develop/docs/ipv6-design-doc.md#background) for ` usev6` and others. [These are quite useful](https://desec.readthedocs.io/en/latest/dyndns/configure.html#manual-configuration-other-systems) to update both A and AAAA records at the same time.

## Current Behavior

You cannot easily update IPv4 and IPv6 at the same time.

## Alternatives Considered

* otherwise we would have to duplicate the config for one domain to support IPv6, as far as I see…
* wait for upstream, the issue is https://github.com/ddclient/ddclient/issues/75 AFAIK.

**Comment by tobbenb** [comment]
Not going to patch anything. When ddclient adds it in a release it will be available in the container.
