### ISSUE TITLE
container logs show no ddclient output

### ISSUE THREAD

**Issue by jasunen** [linuxserver/docker-ddclient#54]
------------------------------

## Expected Behavior

When running ddclient container I should see output of ddclient application in container logs.

## Current Behavior

I see only linuxserver.io container startup messages.
If I exec into container with bash and run manually 'ddclient -foreground -file /config/ddclient.conf' I can see all the output as expected.

## Environment
**OS:** ubuntu
**CPU architecture:** x86_64
**How docker service was installed:** swarm

## Command used to create docker container (run/create/compose/screenshot)

container started in swarm with compose file:
version: "3.9"

x-app-1: &default-ddclient
    image: ghcr.io/linuxserver/ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2h

configs:
  ddclient:
    file: ddclient.conf

services:
  ddclient:
    <<: *default-ddclient 
    configs:
      - source: ddclient
        target: /config/ddclient.conf
        uid: '0'
        gid: '1000'
        mode: 0440

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
chown: changing ownership of '/config/ddclient.conf': Read-only file system,
chmod: changing permissions of '/config/ddclient.conf': Read-only file system,
[cont-init.d] 30-config: exited 1.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Setting up watches.,
Watches established.

**Comment by jasunen** [comment]
my ddclient.conf:
daemon=300
use=web
web=svc.joker.com/nic/checkip
server=svc.joker.com/nic/update?
protocol=dyndns2
login=*******<masked>
password=******<masked>
host=******<masked>
ssl=yes
verbose=yes
quiet=no
debug=no

**Comment by Lockszmith-GH** [comment]
Based on https://github.com/ddclient/ddclient#troubleshooting the `-debug -verbose -noquiet` options are command line options.

What I ended up doing for myself was add the command line switched and bind the file:

1. Create a file named `ddclient.run` place the following code in it:
```bash
#!/usr/bin/with-contenv bash
exec \
	s6-setuidgid abc /usr/bin/ddclient -foreground -debug -verbose -noquiet -file /ddclient.conf
```
2. `chmod` it to `774`
3. `chown` it as `root:root`
4. add the following volume bind:
```docker-compose
./ddclient.run:/etc/services.d/ddclient/run
```
5. start the contianer

I wish this was controllable via an ENVIRONMENT VARIABLE in the docker-config - but for now, it works.

**Comment by hadjilucasL** [comment]
I believe you can just add 

```
verbose=yes
```

in the config file (ddclient.conf) and that should increase the log verbosity. Seems to work when I try it on my side.

The relevant parts of my config file:

```
daemon=650
syslog=yes
pid=/var/run/ddclient/ddclient.pid
cache=/config/ddclient.cache
ssl=yes                                                   
verbose=yes

use=web, web=checkip.dyndns.org/, web-skip='Current IP Address:'
```

**Comment by TheSpad** [comment]
@Lockszmith-GH you're welcome to submit a PR, I don't see we'd have any issue with an ENV to enable debug logging.

**Comment by Lockszmith-GH** [comment]
@TheSpad good point, I might try that, but please - if someone can, don't wait on me - my brain might surprise me and I'll get it done, but I'm betting on the usual - not counting on it.

@hadjilucasL with the risk of sounding pretentious, I'll sarcastically say 'believing isn't seeing' 😉 

What I mean: I saw that config in your original post, this is what brought me here, I had the same issue, I was hoping what you are trying to do would work for me.
So at first I tried it myself, after seeing it didn't work - I reviewed the parent GitHub repo, and noticed those options are not listed there.
<br/>They are only listed as command line options.

The workaround I suggested, worked for me with the current version pulled, and I hope this will work for you as well.

**Comment by hadjilucasL** [comment]
Hey @Lockszmith-GH. I just tried it with a vanilla pull of the latest docker-ddclient and that config works on my side on unraid.

Regarding the verbose not being in the original example conf file, not all options are found inside the example conf. 

However you can see [here](https://github.com/ddclient/ddclient/blob/c44f446d346c57378c4d3227f03b1d6a423cd766/ddclient.in#L476) that the `verbose` option is listed along with others that are found in the conf file, like the `ssl`. I believe if you go through the code you will find they are all read in if they are defined in the conf file.

As a final demo, you can see here that if I run if from the command line, the verbose option is not initially set as it is undefined in the default `opt` and only set after the `globals` are read in from the configuration file.

```
root@b9cc3eb8c814:/# ddclient -file /config/ddclient.conf -foreground -debug -noexec
=== opt ====
opt{cache}                           : <undefined>
opt{cmd}                             : <undefined>
opt{cmd-skip}                        : <undefined>
opt{daemon}                          : 650
opt{debug}                           : 1
opt{exec}                            : 0
opt{facility}                        : <undefined>
opt{file}                            : /config/ddclient.conf
opt{force}                           : <undefined>
opt{foreground}                      : 1
opt{fw}                              : <undefined>
opt{fw-banlocal}                     : <undefined>
opt{fw-login}                        : <undefined>
opt{fw-password}                     : <undefined>
opt{fw-skip}                         : <undefined>
opt{geturl}                          : <undefined>
opt{help}                            : <undefined>
opt{host}                            : <undefined>
opt{if}                              : <undefined>
opt{if-skip}                         : <undefined>
opt{ip}                              : <undefined>
opt{ipv6}                            : <undefined>
opt{login}                           : <undefined>
opt{mail}                            : <undefined>
opt{mail-failure}                    : <undefined>
opt{max-interval}                    : 2160000
opt{min-error-interval}              : 300
opt{min-interval}                    : 30
opt{options}                         : <undefined>
opt{password}                        : <undefined>
opt{pid}                             : <undefined>
opt{postscript}                      : <undefined>
opt{priority}                        : <undefined>
opt{protocol}                        : <undefined>
opt{proxy}                           : <undefined>
opt{query}                           : <undefined>
opt{quiet}                           : 0
opt{retry}                           : <undefined>
opt{server}                          : <undefined>
opt{ssl}                             : <undefined>
opt{syslog}                          : <undefined>
opt{test}                            : <undefined>
opt{timeout}                         : <undefined>
opt{use}                             : <undefined>
opt{verbose}                         : <undefined>
opt{web}                             : <undefined>
opt{web-skip}                        : <undefined>
=== globals ====
globals{cache}                       : /config/ddclient.cache
globals{daemon}                      : 650
globals{debug}                       : 1
globals{exec}                        : 0
globals{file}                        : /config/ddclient.conf
globals{foreground}                  : 1
globals{login}                       : xxxx
globals{password}                    : xxxx
globals{pid}                         : /var/run/ddclient/ddclient.pid
globals{protocol}                    : xxxx
globals{quiet}                       : 0
globals{ssl}                         : 1
globals{syslog}                      : 1
globals{use}                         : web
globals{verbose}                     : 1
globals{web}                         : checkip.dyndns.org/
globals{web-skip}                    : Current IP Address:
=== config ====
config{121254722}{atime}             : 0
config{121254722}{cacheable}         : ARRAY(0x562d288b55e8)
config{121254722}{cmd}               : <undefined>
config{121254722}{cmd-skip}          : 
config{121254722}{fw}                : 
config{121254722}{fw-banlocal}       : 0
config{121254722}{fw-login}          : <undefined>
config{121254722}{fw-password}       : 
config{121254722}{fw-skip}           : 
config{121254722}{host}              : xxxxx
config{121254722}{if}                : ppp0
config{121254722}{if-skip}           : 
config{121254722}{ip}                : <undefined>
config{121254722}{ipv6}              : 0
config{121254722}{login}             : xxxxx
config{121254722}{max-interval}      : 2160000
config{121254722}{min-error-interval} : 300
config{121254722}{min-interval}      : 30
config{121254722}{mtime}             : 0
config{121254722}{password}          : xxxxxx
config{121254722}{protocol}          : xxxx
config{121254722}{script}            : /servlet/updateip
config{121254722}{server}            : xxxxxx
config{121254722}{status}            : 
config{121254722}{use}               : web
config{121254722}{warned-min-error-interval} : 0
config{121254722}{warned-min-interval} : 0
config{121254722}{web}               : checkip.dyndns.org/
config{121254722}{web-skip}          : Current IP Address:
config{121254722}{wtime}             : 30
```

**Comment by Lockszmith-GH** [comment]
You are completely right about the code, looks like it's been there at least 2 years ago, if not from the beginning. I'll try to re-pull and reconfigure, see if that works out.

What about OP (@jasunen) did anything here work for you?

**Comment by julmb** [comment]
I am having the same problem. However, log output is only missing when the `daemon=` option is set in the configuration file. I believe that some very strange things are happening here.

In the container, ddclient is run as `/usr/bin/ddclient -foreground -file /ddclient.conf`. This actually does not start a persistent service, but only runs the client once. When the client then exits almost immediately, it is restarted by the s6 supervisor (see also https://github.com/ddclient/ddclient/issues/352#issuecomment-920051993). I suspect the only reason this does not cause a very fast restart loop is that ddclient will wait for a minimum of 60 seconds if no update interval is configured (see https://github.com/ddclient/ddclient/issues/352#issuecomment-918519239).

When the `daemon=` option is set, this overrides the `-foreground` behavior and starts ddclient as a persistent service. However, it also seems to change where the output is sent. I have not yet been able to figure out why this is and how to influence it. Setting both `syslog=yes` and `verbose=yes` as @hadjilucasL recommends restores at least some of the output (maybe it gets sent to stderr for debug purposes?), but it seems like a bit of a hack.

So right now my options are
1. not setting `daemon=` and have s6 continuously restart ddclient every minute, which is too fast and gets me blocked by my DDNS provider
2. setting `daemon=` and have ddclient runs properly as a daemon but with either no output or very verbose debug output

I seems like way ddclient is run in the container is somewhat broken and maybe there is a better and more consistent way to handle things. Setting the update interval via `daemon=` should ideally not fundamentally change how the service is run and also break logging at the same time.
