### ISSUE TITLE
Healthcheck for ddclient

### ISSUE THREAD

**Issue by SchoolGuy** [linuxserver/docker-ddclient#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

It would be helpful to have a health-check available for the image to be able to tell if the container is responsive.

## Current Behavior

Currently the fact that the container is running is indicating that ddclient is working, this is however an assumption that is not true in all cases.

## Alternatives Considered

None

## Context

- Docker: https://docs.docker.com/engine/reference/builder/#healthcheck
- K8s: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by Roxedus** [comment]
We are currently not interested in implementing healtchecks because of:
* Its nothing but informational from a docker standpoint
* Its something we would have to implement on all images.

**Comment by SchoolGuy** [comment]
To be honest I find that having a health-check on all images as a very reasonable thing. It is informational but it is important information. The situation i described can happen to any daemon. In case the environment has little resources left it may be that such a situation is occurring and thus a container restart would help in solving such an unresponsive container. With a health-check this can be done automatically.

**Comment by aptalca** [comment]
You can add your own healthcheck runtime

https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Comment by SchoolGuy** [comment]
@aptalca I am very well aware. Since I am in a k8s env, I would do this anyway. I just wanted to raise this feature as it is beneficial for everyone imho.
