### ISSUE TITLE
[BUG] Cannot get ip with 2023-02-27 19:33:39 image

### ISSUE THREAD

**Issue by ams123ios** [linuxserver/docker-ddclient#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Receiving error when updating IP address.

WARNING:  cannot connect to checkip.dyndns.org:443 socket: Connection refused IO::Socket::IP configuration failed
WARNING:  found neither IPv4 nor IPv6 address

Recreated config file change

`daemon=3600
syslog=yes
pid=/var/run/ddclient/ddclient.pid
ssl=yes`

`use=web`

To debug I ran the following from the container console and received the correct IP address in response.
content=$(wget checkip.dyndns.org -q -O -)
echo $content

### Expected Behavior

Receiving correct IP from checkip.dyndns.org

### Steps To Reproduce

Auto update produces issue

### Environment

```markdown
- OS:  Ubuntu 20.04
- How docker service was installed:  apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los-Angeles
    volumes:
      - /home/docker/compose/ddclient/config:/config
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[custom-init] No custom files found, skipping...
Setting up watches.
Watches established.
[ls.io-init] done.
WARNING:  cannot connect to checkip.dyndns.org:443 socket: Connection refused IO::Socket::IP configuration failed
WARNING:  found neither IPv4 nor IPv6 address
[migrations] started
[migrations] no migrations found
usermod: no changes
```

**Comment by ams123ios** [comment]
Closing issue.  ddclint is defaluting to 443 but HTTPS is not supported by checkip.dyndns.org

**Comment by drizuid** [comment]
OP said closing but didn't close. closing :)
