### ISSUE TITLE
[FEAT] Allow read-only mounted config

### ISSUE THREAD

**Issue by pskopnik** [linuxserver/docker-ddclient#68]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The configuration file `ddclient.conf` should be read-only mountable into the container, for example by using the [Docker Configs](https://docs.docker.com/engine/swarm/configs/) mechanism.

Right now this is not possible because a start up script attempts to change the ownership and permission bits of the `/config/ddclient.conf` file. This fails on a read-only mount.

A read-only mount used to be possible before 3fd428ce0a59c24ed5c0ae27bc6b80971d8af5b9 which switched to the new dependency based s6 start up. If the [`init-ddclient-config`](https://github.com/linuxserver/docker-ddclient/blob/master/root/etc/s6-overlay/s6-rc.d/init-ddclient-config/run) job fails, no services are started.
Before 3fd428ce0a59c24ed5c0ae27bc6b80971d8af5b9, services were started even if the equivalent of `init-ddclient-config` failed.

### Reason for change

Read-only mounting configuration has become a common pattern to ensure the files cannot be changed from inside containers.
There are features in Docker and Kubernetes to easily support these operations.

### Proposed code change

Either the ownership & permission changes on the config directory are be dropped or made optional.
Or, the read-only input configuration (if optionally present) is copied to the `/config/ddclient.conf` configuration on start up.

**Comment by pskopnik** [comment]
One possibility is for a user to drop a script into `/custom-cont-init.d/`. The script can copy the read-only mounted `ddclient.conf` to `/config/ddclient.conf`.

**Comment by aptalca** [comment]
To be clear, we do not consider it a bug as we require the config folder to be writable and bind mounted to a local folder (always have)

The config folder is ours (the container's) to manage, other media or data folders are yours (when applicable)

**Comment by SchoolGuy** [comment]
Okay fine for me but how do I pass read-only configuration options into the container? I definitely don't want my passwords world readable in cleartext in my k8s cluster because I must use a ConfigMap...

The options provided by this image don't allow you to change them without touching the configuration file directly.

**Comment by aptalca** [comment]
> Edit: Are you implying we should use a PVC for a single file that is on top of that a configuration file?

Not implying, I explicitly stated that: `we require the config folder to be writable and bind mounted to a local folder`

We don't specifically support k8s or its specific features like ConfigMap.
We also don't support config folders residing on remote shares like nfs. Local map or block storage like longhorn are fine.

**Comment by SchoolGuy** [comment]
@aptalca Can we please change that? Volumes are really not thought for storing configuration...

**Comment by Roxedus** [comment]
Volumes are a mechanism for storing persistent data, in this image, configuration files are classified as persistent data. So yes, our /config mount is meant to store configurations.

**Comment by pskopnik** [comment]
Could you reason why you are rejecting this feature request?
E.g. perhaps it's already possible, you deem it an edge-case, ...

**Comment by Roxedus** [comment]
It is our defacto design choice across all our 170+ images. You can counter your edge-case with a edge-case solution; a sidecar and /config as a tmpfs volume.
