### ISSUE TITLE
[FEAT] Update get-ip-from-fritzbox script

### ISSUE THREAD

**Issue by Kalvalax** [linuxserver/docker-ddclient#74]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The updated sample-get-ip-from-fritzbox script from ddclient/ddclient now can pass the ip/hostname of the fritzbox to use the script also when 'fritz.box' can't be resolved by using the optional environment variable FRITZ_BOX_HOSTNAME.

### Reason for change

this image can't be used if fritz.box vcan_t be resolved.

### Proposed code change

The changed script can be found here:
https://github.com/ddclient/ddclient/blob/master/sample-get-ip-from-fritzbox

**Comment by aptalca** [comment]
I'm confused as to what you are asking us to do. We build their latest releases. When they put out a release with that commit, it will be in the image.

**Comment by Kalvalax** [comment]
Did you check th elink to the github repository? This shows the modified script:
https://github.com/ddclient/ddclient/blob/master/sample-get-ip-from-fritzbox

It now contains the following code solving my issue:

# Set default hostname to connect to the FritzBox
: ${FRITZ_BOX_HOSTNAME:=fritz.box}

curl -s -H 'Content-Type: text/xml; charset="utf-8"' \
-H 'SOAPAction: urn:schemas-upnp-org:service:WANIPConnection:1#GetExternalIPAddress' \
-d '<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:GetExternalIPAddress xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1" /></s:Body></s:Envelope>' \
"http://$FRITZ_BOX_HOSTNAME:49000/igdupnp/control/WANIPConn1" | \ grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'

Viele Grüße / Kind regards
Kalvalax

------- Original Message -------
aptalca ***@***.***> schrieb am Freitag, 29. September 2023 um 00:20:

**Comment by j0nnymoe** [comment]
They haven't cut a release since that was added. It'll be in our container once they cut a release.
