### ISSUE TITLE
[FEAT] <Add support for IPV6>

### ISSUE THREAD

**Issue by d-dandrew** [linuxserver/docker-ddclient#75]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Cant start the docker-ddclient with the default docker-compose script 
Its confirmed that docker daemon has enabled IPV6 support
`docker network inspect ddclient_default` shows `“EnableIPv6”: false` which means ddclient cant access to IPV6 network 

### Reason for change

ddclient can get ipv6 address on bare metal machine but cant access to ipv6 with lsio image

**Comment by Roxedus** [comment]
first step is to ensure the container has a ipv6 address

**Comment by drizuid** [comment]
> Its confirmed that docker daemon has enabled IPV6 support

Its confirmed that docker daemon has enabled IPV6 support` that applies only to the default bridge


> `docker network inspect ddclient_default` shows `“EnableIPv6”: false` which means ddclient cant access to IPV6 network

which means the custom bridge you have ddclient in is not ipv6 enabled.
this is not something we can fix for you. create your custom bridge with ipv6 enabled
