### ISSUE TITLE
[BUG] ddclient stuck in "curl could not connect to X" loop #730

### ISSUE THREAD

**Issue by kilrau** [linuxserver/docker-ddclient#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cross posting this here as ddclient team suggests this could be related to the docker container. Original issue: https://github.com/ddclient/ddclient/issues/730. When a dns resolution of a dyndns endpoint fails, ddclient gets stuck in a `"curl could not connect to X` and doesn't exit when dyndns endpoint is reachable again. Only fix is to restart the container.

### Expected Behavior

Dyndns endpoint is reachable, resolution works.

### Steps To Reproduce

1. run this image updating to an e.g. namecheap dyndns endpoint
2. bring endpoint offline when ddclient is trying to resolve
3. watch infinity loop

### Environment

```markdown
- OS: Ubuntu 20.04. LTS
- How docker service was installed: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
```

### CPU architecture

x86-64

### Docker creation

```bash
docker-compose.yml

services:
  ddclient-mydomain.com:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient-mydomain.com
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Berlin
    volumes:
      - /path/to/config
    restart: unless-stopped
```

### Container logs

```bash
Infinity loop of:

WARNING:  CURL error (6) Couldn't resolve host. The given remote host was not resolved.
WARNING:  curl cannot connect to https://dynamicdns.park-your-domain.com using IPv0
WARNING:  found neither IPv4 nor IPv6 address
WARNING:  Could not determine an IP for @
WARNING:  CURL error (6) Couldn't resolve host. The given remote host was not resolved.
WARNING:  curl cannot connect to https://dynamicdns.park-your-domain.com using IPv0
WARNING:  found neither IPv4 nor IPv6 address
WARNING:  Could not determine an IP for @
```

**Comment by kilrau** [comment]
so why did it work immediately when I restarted the container?

**Comment by Roxedus** [comment]
Intermediate networking issues occur. hard to say without more data. We don't explicitly handle dns or curl in the container.
