### ISSUE TITLE
[BUG] The `arm32v7-latest` tag on dockerhub actually points to a `arm64` build

### ISSUE THREAD

**Issue by Lorilandly** [linuxserver/docker-ddclient#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `arm32v7-latest` tag on dockerhub actually points to a `arm64` build. I understand that arm32 is not supported anymore, but this is a really small thing to fix and drastically improve the experience of a user looking for an older version of ddclient.
![Screenshot 2024-09-07 at 10 16 21 PM](https://github.com/user-attachments/assets/93228e41-d426-47ce-b4e2-091a2bac5b60)

### Expected Behavior

The `arm32v7-latest` tag should point to a 'armv7' build

### Steps To Reproduce

1. go to dockerhub
2. look at the `arm32v7-latest` tag

### Environment

```markdown
- OS: raspbian
- How docker service was installed:
distro's package manager
```

### CPU architecture

arm64

### Docker creation

```bash
do not matter
```

### Container logs

```bash
do not matter
```

**Comment by aptalca** [comment]
It's intentional
https://info.linuxserver.io/issues/2024-08-11-deprecation-changes/
