### ISSUE TITLE
Development branch / IPv6 Support

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-ddclient#9]
This is the only output I get from the docker console after 1 hour:

```
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/

-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1004
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
Setting up watches.
Watches established.
[services.d] done.
```

**Comment by aptalca** [comment]
I believe it's working as intended as long as you don't get error messages every five minutes.

If you really want to test, try changing the ip manually on your service (ie. cloudflare) and wait five minutes to see whether ddclient corrects it

**Comment by jwillmer** [comment]
Isn't there a log that I can open to see what it does?
- Does it get the correct WAN IP
- Does it get access to cloudflare / does it modify the right record

**Comment by aptalca** [comment]
I believe ddclient only logs errors. Quick online search revealed many similar questions about it

**Comment by jwillmer** [comment]
Today my WAN connection broke down and I got a new IPv6 so I could observe that it did not work. This problem is that in the current build the IPv6 support is missing.  It was already [fixed in 2016](https://github.com/ddclient/ddclient/commit/dc01f09224a17f493a43a219cd9a71c96c5054ee) but there was no new release since then. Specifically [this option is missing](https://github.com/ddclient/ddclient/blob/ec2acfb1f3a8043ac993765a1709e5798ff7d267/ddclient#L747) in the current build. Could we get a development build (current master branch)?

**Comment by aptalca** [comment]
Thanks for reporting. The maintainer is looking into it

**Comment by tobbenb** [comment]
@jwillmer I'll look into adding the IPv6 support. Do you know if the switch needs to be set to enable IPv6?

**Comment by aptalca** [comment]
See this commit from a few days ago. It adds ipv6 to cloudflare: https://github.com/ddclient/ddclient/commit/ec2acfb1f3a8043ac993765a1709e5798ff7d267

**Comment by jwillmer** [comment]
This is the part there they try to get the IPv6: [line 2042](https://github.com/ddclient/ddclient/blob/ec2acfb1f3a8043ac993765a1709e5798ff7d267/ddclient#L2042-L2051)

and then they change the query if the got an IPv6:
```
if (is_ipv6($ip)) {
	$url .= "type=AAAA&name=$domain";
} else {
	$url .= "type=A&name=$domain";
}
```

From scanning the source code I guess you need to include additional libraries to the docker image:

```
Error loading the Perl module IO::Socket::INET6 needed for ipv6 connect.
On Debian, the package libio-socket-inet6-perl must be installed.
On Red Hat, the package perl-IO-Socket-INET6 must be installed.
On Alpine, the package perl-io-socket-inet6 must be installed.
EOM
```

**Comment by jwillmer** [comment]
I am actually not sure if the current dev branch implementation works with IPv6 when an IPv4 is present. It looks like they first check IPv4 and if that is not available and IPv6 flag is set it will use IPv6 but I could be wrong since the code is not very structured.
